/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProductCollectionsInterface;
import dao.ProductsDatabaseManagement;
//import dao.Products_list;
import domain.Product;
import gui.helpers.SimpleListModel;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author monvi967
 */
public class ProductReport extends javax.swing.JDialog {
     SimpleListModel productDisplay = new SimpleListModel();
     SimpleListModel categoryDisplay = new SimpleListModel();
     Product selectedProduct = new Product();
     ProductCollectionsInterface products = new ProductsDatabaseManagement();
     
     
    /**
     * Creates new form Product_report
     * @param parent
     * @param modal
     */
    public ProductReport(java.awt.Frame parent, boolean modal,ProductCollectionsInterface pdtList ) {
        super(parent, modal);
        initComponents();
        
        this.products = pdtList;
        
        productDisplay.updateItems(products.get());
        categoryDisplay.updateItems(products.getCategories());
        listProducts.setModel(productDisplay);
        categoryComboBox.setModel(categoryDisplay);
        
        categoryComboBox.addItem("all");
        if(categoryComboBox.getSelectedItem() == null){
            categoryComboBox.setSelectedItem("all");
        }
        if(categoryComboBox.getSelectedItem() == "all"){
            productDisplay.updateItems(products.get());
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listProducts = new javax.swing.JList();
        exitReport = new javax.swing.JButton();
        categoryComboBox = new javax.swing.JComboBox();
        categoryLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchIDbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listProducts.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listProducts);

        exitReport.setText("Close");
        exitReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitReportActionPerformed(evt);
            }
        });

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                categoryComboBoxItemStateChanged(evt);
            }
        });
        categoryComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryComboBoxMouseClicked(evt);
            }
        });
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        categoryLabel.setText("Category");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        searchLabel.setText("Search by ID");

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        searchIDbutton.setText("Search");
        searchIDbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton)
                        .addGap(90, 90, 90)
                        .addComponent(exitReport))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(categoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchIDbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchIDbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitReport)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitReportActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitReportActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
       if (listProducts.isSelectionEmpty() == true) {
            return;
        }

        selectedProduct = (Product) listProducts.getSelectedValue();
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this?");

        if (result == JOptionPane.YES_OPTION) {
            products.delete(selectedProduct);
        }
        productDisplay.updateItems(products.get());
        categoryDisplay.updateItems(products.getCategories());
        listProducts.setModel(productDisplay);
        categoryComboBox.setModel(categoryDisplay);
        
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        selectedProduct = (Product) listProducts.getSelectedValue();
        if(selectedProduct != null){
            ProductEntry productEntry = new ProductEntry(this, true, selectedProduct, products);
            productEntry.setLocationRelativeTo(this);
            productEntry.setVisible(true);
            
            //System.out.println("report edit Finish " + Product_entry.selcat);
           // Product_entry.selcat = null;
            //System.out.println("report selcat set to non " + Product_entry.selcat);
            
            productDisplay.updateItems(products.get());
            categoryDisplay.updateItems(products.getCategories());
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void searchIDbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDbuttonActionPerformed
        // TODO add your handling code here:
        Product pdt = products.search_by_ID(Integer.valueOf(searchTextField.getText()));
        if(pdt != null){
            productDisplay.updateItems(pdt);
            categoryDisplay.updateItems(products.getCategories());
            
        }
        return;
    }//GEN-LAST:event_searchIDbuttonActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:
        Set<Product> pdts = products.getCatSet((String) categoryComboBox.getSelectedItem());
        
        if(pdts != null){
            productDisplay.updateItems(pdts);
            listProducts.setModel(productDisplay);
        }

        //categoryComboBox.setModel(categoryDisplay);
        productDisplay.updateItems(pdts);
        categoryDisplay.updateItems(products.getCategories());
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void categoryComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_categoryComboBoxItemStateChanged
        // TODO add your handling code here:
       

    }//GEN-LAST:event_categoryComboBoxItemStateChanged

    private void categoryComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryComboBoxMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_categoryComboBoxMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton exitReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listProducts;
    private javax.swing.JButton searchIDbutton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
