create table product(   
    product_ID integer not null,
    name varchar not null,
    description varchar,
    category varchar,
    price decimal(12,2),
    stock_quantity integer,
    
    constraint pk_product primary key (product_ID)
);

create table Customer(   
    customer_ID varchar not null,
    name varchar not null,
    email varchar,
    address varchar,
    credit_card integer not null,
    password varchar not null,
    
    constraint pk_customer primary key (customer_ID)
);

create table Order_sale(   
    order_ID integer generated by default as identity (start with 1000) not null, 
    order_date timestamp not null,
    
    constraint pk_Order_sale primary key (order_ID)
);

create table Order_item(
    sale_id integer not null,
    quantity_purchased integer not null,
    purchase_price decimal(12,2),

    constraint pk_order_item primary key (sale_id), 
    constraint fk_order_item_sale_id foreign key (sale_id) references order_sale(order_id), 

);

